server:
  port: 8081

spring:
  application:
    name: vp-analytics-ms-ingestion
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
  show-sql: false
  hibernate:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      compression-type: lz4
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    transactions-ingested: vpa.transactions.ingested